#This is to summarize the mean and sd of SFS generated by get_SFS_from_ms_general_reps.py:

import sys
import os
import numpy

f_sfs = open(sys.argv[1], 'r') #this file has count information.
f_name = sys.argv[1]
result = open(f_name.split(".")[0] + "_summary.sfs", 'w+')
d_freq = {}
l_af = []
for line in f_sfs:
    line1 = line.strip('\n')
    line2 = line1.split('\t')
    if line2[0] == "filename":
        result.write(line1.replace("filename", "stat") + '\n')
        for x in line2:
            if "file" not in x:
                d_freq[x] = []
                l_af.append(x)
    else:
        l_counts = line2[1:]
        #calculate sum
        s_tot = 0
        for x in l_counts:
            s_tot += int(x)
        #calculate frequency
        l_freq = []
        for x in l_counts:
            l_freq.append(float(x)/float(s_tot))
        #add to dictionary
        s_af = 1
        for x in l_freq:
            d_freq[str(s_af)].append(x)
            s_af += 1
f_sfs.close()

result.write("mean")
for AF in l_af:
    result.write('\t' + str(numpy.mean(d_freq[AF])))
result.write('\n')
result.write("sd")
for AF in l_af:
    result.write('\t' + str(numpy.std(d_freq[AF])))
result.write('\n')

result.close()
print ("done")



